#!/bin/sh

HOME_DIR=$(git rev-parse --show-toplevel)
DIFF_FILES=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- "*.cs")

echo "Auto formatting for the project by dotnet-format"
echo "$(pwd)"

if [ -z "${DIFF_FILES}" ]; then
  exit 0
else
  echo "The following source codes are modified"
  echo "${DIFF_FILES}"
  dotnet format ${HOME_DIR}/*.sln
  if [ $? -ne 0 ]; then
    echo "Dotnet format failed, please fix code and recommit"
    exit 1
  fi
  git add .
fi

echo "Check code style by StyleCop"

./Scripts/git_hooks/StyleCopCLI/StyleCopCLI.exe -sln ${HOME_DIR}/*.sln -set stylecop.json
if [ $? -ne 0 ]; then
  exit 1
fi

exit 0