#!/bin/sh

HOME_DIR=$(git rev-parse --show-toplevel)
DIFF_FILES=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- "*.cs")

echo "Auto formatting for the project by dotnet-format"
echo "$(pwd)"

if [ -z "${DIFF_FILES}" ]; then
  echo "There is no source code change"
else
  echo "The following source codes are modified"
  echo "${DIFF_FILES}"
  dotnet format ${HOME_DIR}/*.sln
  if [ $? -ne 0 ]; then
    echo "Dotnet format failed, please fix code and recommit"
    exit 1
  fi
  git add .
fi

echo "Check code style by StyleCop"

STYLE_CHECK_COMMAND="dotnet ./Scripts/git_hooks/StyleCop.Analyzers/StyleCopAnalyzers.CLI.dll check ./"
STYLE_CHECK_RESULT=`${STYLE_CHECK_COMMAND}`

if [ $? -ne 0 ]; then
  echo "${STYLE_CHECK_RESULT}"
  exit 1
fi

echo "Code style check is over"

exit 0