#!/bin/sh

HOME_DIR=$(git rev-parse --show-toplevel)
DIFF_FILES =$(git diff --exit-code --name-only --diff-filter=ACM "*.cs")

echo "Auto formatting for the project by dotnet-format"

if [ -z "${FILES}" ]; then
  exit 0
else
  echo "The following source codes are modified"
  dotnet format ${HOME_DIR}/*.sln
fi

exit 0